/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items?: Array<{
    reference?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPage'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'research'
        }
    label?: string
    _type: 'internal'
    _key: string
  }>
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title: string
  subtext: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  latest?: {
    title: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    items?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'work'
    }>
  }
  wip?: {
    title: string
    items?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'work'
    }>
  }
  articles?: {
    title: string
    items?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'blog'
    }>
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  info: {
    thumbnail: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    email: string
    resume: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
      }
      media?: unknown
      _type: 'file'
    }
    social?: {
      twitter?: string
      linkedin?: string
      github?: string
    }
  }
  title: string
  description: string
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  date?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    alt?: string
    _type: 'image'
  }
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Work = {
  _id: string
  _type: 'work'
  _createdAt: string
  _updatedAt: string
  _rev: string
  label: string
  title: string
  year?: string
  subtext?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  type: 'link' | 'page' | 'file' | 'progress'
  link?: string
  page?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPage'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'research'
      }
  file?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
}

export type Research = {
  _id: string
  _type: 'research'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: string
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow: string
  title: string
  slug: Slug
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Menu
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Blog
  | Slug
  | Work
  | Research
  | BlogPage
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0] {  ...,  info {    ...,    "resume": resume.asset->url  }}
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  info: {
    thumbnail: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    email: string
    resume: string | null
    social?: {
      twitter?: string
      linkedin?: string
      github?: string
    }
  }
  title: string
  description: string
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
} | null
// Variable: menuQuery
// Query: *[_type == "menu"][0] {  ...,  items[] {    "_key": _key,    "_type": _type,    "label": label,    "slug": select(      reference->_type == "research" => "research",      reference->_type == "blogPage" => "blog",      reference->slug.current    ),    "document": reference->_type  },}
export type MenuQueryResult = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items: Array<{
    _key: string
    _type: 'internal'
    label: string | null
    slug: string | 'blog' | 'research' | null
    document: 'blogPage' | 'page' | 'research' | null
  }> | null
} | null
// Variable: homepageQuery
// Query: *[_type == "homepage"][0] {    ...,    latest {      'title': title,      'description': description,      'items': items[]-> {        ...,        "label": label,        "title": title,        "subtext": subtext,        "type": type,        "file": file.asset->url,        "link": link,        "page": select(          page->_type == "research" => "research",          page->_type == "blogPage" => "blog",          page->slug.current        ),      },    },    wip {      'title': title,      'items': items[]-> {        ...,        "label": label,        "title": title,        "subtext": subtext,        "type": type,        "file": file.asset->url,        "link": link,        "page": select(          page->_type == "research" => "research",          page->_type == "blogPage" => "blog",          page->slug.current        ),      },    },    articles {      'title': title,      'items': items[]-> {        ...,        "title": title,        "excerpt": excerpt,        "image": image,        "date": date,        "slug": slug.current,      },    }  }
export type HomepageQueryResult = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title: string
  subtext: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  latest: {
    title: string
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    items: Array<{
      _id: string
      _type: 'work'
      _createdAt: string
      _updatedAt: string
      _rev: string
      label: string
      title: string
      year?: string
      subtext: string | null
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      }
      type: 'file' | 'link' | 'page' | 'progress'
      link: string | null
      page: string | 'blog' | 'research' | null
      file: string | null
    }> | null
  } | null
  wip: {
    title: string
    items: Array<{
      _id: string
      _type: 'work'
      _createdAt: string
      _updatedAt: string
      _rev: string
      label: string
      title: string
      year?: string
      subtext: string | null
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      }
      type: 'file' | 'link' | 'page' | 'progress'
      link: string | null
      page: string | 'blog' | 'research' | null
      file: string | null
    }> | null
  } | null
  articles: {
    title: string
    items: Array<{
      _id: string
      _type: 'blog'
      _createdAt: string
      _updatedAt: string
      _rev: string
      title: string
      slug: string
      excerpt: string | null
      date: string | null
      image: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
      } | null
      content?: Array<
        | {
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal'
            listItem?: 'bullet' | 'number'
            markDefs?: Array<{
              href?: string
              _type: 'link'
              _key: string
            }>
            level?: number
            _type: 'block'
            _key: string
          }
        | {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            caption?: string
            alt?: string
            _type: 'image'
            _key: string
          }
      >
    }> | null
  } | null
} | null
// Variable: blogPostBySlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0] {    ...,    "related": *[_type == "blog" && _id != ^._id][0...3] {      ...,      "title": title,      "excerpt": excerpt,      "image": image,      "date": date,      "slug": slug.current,    }  }
export type BlogPostBySlugQueryResult = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  date?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    alt?: string
    _type: 'image'
  }
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
  related: Array<{
    _id: string
    _type: 'blog'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string
    slug: string
    excerpt: string | null
    date: string | null
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      caption?: string
      alt?: string
      _type: 'image'
    } | null
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          caption?: string
          alt?: string
          _type: 'image'
          _key: string
        }
    >
  }>
} | null
// Variable: blogQuery
// Query: *[_type == "blogPage"][0] {    ...,    "items": *[_type == "blog"] {      ...,      "title": title,      "excerpt": excerpt,      "image": image,      "date": date,      "slug": slug.current,    }  }
export type BlogQueryResult = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: string
  items: Array<{
    _id: string
    _type: 'blog'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string
    slug: string
    excerpt: string | null
    date: string | null
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      caption?: string
      alt?: string
      _type: 'image'
    } | null
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          caption?: string
          alt?: string
          _type: 'image'
          _key: string
        }
    >
  }>
} | null
// Variable: workQuery
// Query: *[_type == "research"][0] {    ...,    "items": *[_type == "work"] {      ...,      "label": label,      "title": title,      "subtext": subtext,      "type": type,      "file": file.asset->url,      "link": link,      "page": select(        page->_type == "research" => "research",        page->_type == "blogPage" => "blog",        page->slug.current      ),    }  }
export type WorkQueryResult = {
  _id: string
  _type: 'research'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: string
  items: Array<{
    _id: string
    _type: 'work'
    _createdAt: string
    _updatedAt: string
    _rev: string
    label: string
    title: string
    year?: string
    subtext: string | null
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    type: 'file' | 'link' | 'page' | 'progress'
    link: string | null
    page: string | 'blog' | 'research' | null
    file: string | null
  }>
} | null
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    ...,    "work": *[_type == "work"] | order(_createdAt desc)[0...6] {      ...,      "label": label,      "title": title,      "subtext": subtext,      "type": type,      "file": file.asset->url,      "link": link,      "page": select(        page->_type == "research" => "research",        page->_type == "blogPage" => "blog",        page->slug.current      ),    }  }
export type PageBySlugQueryResult = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow: string
  title: string
  slug: Slug
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  work: Array<{
    _id: string
    _type: 'work'
    _createdAt: string
    _updatedAt: string
    _rev: string
    label: string
    title: string
    year?: string
    subtext: string | null
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    type: 'file' | 'link' | 'page' | 'progress'
    link: string | null
    page: string | 'blog' | 'research' | null
    file: string | null
  }>
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0] {\n  ...,\n  info {\n    ...,\n    "resume": resume.asset->url\n  }\n}': SettingsQueryResult
    '*[_type == "menu"][0] {\n  ...,\n  items[] {\n    "_key": _key,\n    "_type": _type,\n    "label": label,\n    "slug": select(\n      reference->_type == "research" => "research",\n      reference->_type == "blogPage" => "blog",\n      reference->slug.current\n    ),\n    "document": reference->_type\n  },\n}': MenuQueryResult
    '\n  *[_type == "homepage"][0] {\n    ...,\n    latest {\n      \'title\': title,\n      \'description\': description,\n      \'items\': items[]-> {\n        ...,\n        "label": label,\n        "title": title,\n        "subtext": subtext,\n        "type": type,\n        "file": file.asset->url,\n        "link": link,\n        "page": select(\n          page->_type == "research" => "research",\n          page->_type == "blogPage" => "blog",\n          page->slug.current\n        ),\n      },\n    },\n    wip {\n      \'title\': title,\n      \'items\': items[]-> {\n        ...,\n        "label": label,\n        "title": title,\n        "subtext": subtext,\n        "type": type,\n        "file": file.asset->url,\n        "link": link,\n        "page": select(\n          page->_type == "research" => "research",\n          page->_type == "blogPage" => "blog",\n          page->slug.current\n        ),\n      },\n    },\n    articles {\n      \'title\': title,\n      \'items\': items[]-> {\n        ...,\n        "title": title,\n        "excerpt": excerpt,\n        "image": image,\n        "date": date,\n        "slug": slug.current,\n      },\n    }\n  }\n': HomepageQueryResult
    '\n  *[_type == "blog" && slug.current == $slug][0] {\n    ...,\n    "related": *[_type == "blog" && _id != ^._id][0...3] {\n      ...,\n      "title": title,\n      "excerpt": excerpt,\n      "image": image,\n      "date": date,\n      "slug": slug.current,\n    }\n  }\n': BlogPostBySlugQueryResult
    '\n  *[_type == "blogPage"][0] {\n    ...,\n    "items": *[_type == "blog"] {\n      ...,\n      "title": title,\n      "excerpt": excerpt,\n      "image": image,\n      "date": date,\n      "slug": slug.current,\n    }\n  }\n': BlogQueryResult
    '\n  *[_type == "research"][0] {\n    ...,\n    "items": *[_type == "work"] {\n      ...,\n      "label": label,\n      "title": title,\n      "subtext": subtext,\n      "type": type,\n      "file": file.asset->url,\n      "link": link,\n      "page": select(\n        page->_type == "research" => "research",\n        page->_type == "blogPage" => "blog",\n        page->slug.current\n      ),\n    }\n  }\n': WorkQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    ...,\n    "work": *[_type == "work"] | order(_createdAt desc)[0...6] {\n      ...,\n      "label": label,\n      "title": title,\n      "subtext": subtext,\n      "type": type,\n      "file": file.asset->url,\n      "link": link,\n      "page": select(\n        page->_type == "research" => "research",\n        page->_type == "blogPage" => "blog",\n        page->slug.current\n      ),\n    }\n  }\n': PageBySlugQueryResult
  }
}
